#!/usr/bin/env php
# PHP REPL/Shell v0.8b		(c) 2003-<?= date('Y') ?> Weston Cann, GPL2 license 
# runtime: <?= PHP_BINARY ?> (<?= phpversion(); ?>)
# script:  <?= __FILE__ ?> 
<?php 
date_default_timezone_set("utc");
ini_set('display_errors',1);
set_include_path(get_include_path() . PATH_SEPARATOR. dirname(__FILE__));
set_error_handler('phpsh_throw_error_exception',E_ALL);
register_shutdown_function('phpsh_on_shutdown');
define('DEFAULT_CRASH','phpsh_crash.hist');
define('DEFAULT_HIST','phpsh.hist');
define('MAIN_PROMPT','phpsh> ');
define('CONT_PROMPT','  ...> ');
$history = [];

if(isset($argv)) { // process arguments as php to execute
	foreach($argv as $arg) 
		if($arg != "-r") 
			phpsh_include($arg);
		else
			phpsh_include(DEFAULT_CRASH); 
}

if(is_callable("readline")) { // figure out our readline strategy
	print "# phpsh_readln -> readline\n";
	
	function phpsh_readln($prompt) { 
		return rtrim(readline($prompt)); 
	}
} else {
	print "# phpsh_readln -> /dev/stdin \n";
	print "# (add libreadline or libedit to your php runtime for a better experience!) \n";
	function phpsh_readln($prompt) {
		print $prompt;
		$fp=fopen("/dev/stdin", "r");
    	$input=fgets($fp, 4096);
    	fclose($fp);
    	return rtrim($input);
	}
}

print "# Enter .h for help\n\n";

phpsh_repl:
do { // main read-eval-print loop

	$entry = phpsh_read_entry();
	/* returns: 
	     null   | if the entry/line is empty => null
	     string | if the entry/line if starts w dot & is non-numeric 
	     array (w keys 'code' & 'last') | all other cases

	   So let's handle each case:  
     */
	
	if(empty($entry))                             // easy case!
		continue;

	if(is_string($entry) && $entry[0] == '.') {   // phpsh command
		phpsh_cmd(substr($entry,1));
		continue;
	}

	// otherwise we *should* have an array with keys 'code' & 'last' 
	if($entry['last'] == ';' || $entry['last'] == '}') { 
		// "instructions" statement or block definiton: no return Value
		$evalExp = $entry['code'];
		$type = 'instructions';
	} else if(isset($entry['code'])) {
		// expression: we want to display the value
		$evalExp = "return({$entry['code']});";
		$type = 'expression';
	} else {
		echo "🍅 unexpected entry",phpsh_showVar($entry),"\n";
		$evalExp = "\"🍅 can't process unexpected entry\"";
	}

	try {
		$_ = eval($evalExp);
		if($type == 'expression')
			echo phpsh_showVar($_),"\n"; 
		$history[] = $entry['code'];	
		if(function_exists('readline_add_history'))
			readline_add_history($entry['code']);
	} catch(ParseError $_e) {
		echo "CAUGHT parse error",$_e,"\n";
	} catch(\Throwable $_e) {
		echo "CAUGHT throwable ",$_e,"\n";
	}
	
} while(TRUE);

function phpsh_throw_error_exception($number = 0, $str = '',$file = null,$line = null) {
	throw new ErrorException($str, 0, $number, $file, $line);
	die("control flow shouldn't ever reach here");
}

function phpsh_line_analyze($line) {
	$brace_depth_chg = 0;
	$toks = token_get_all('<?php '.trim($line));
	foreach($toks as $t) {
		switch($t[0] ?? $t) {
			case '{': 
			case T_CURLY_OPEN: $brace_depth_chg++; break;
			//case T_CURLY_CLOSE: doesn't exist? What?
			case '}': $brace_depth_chg--; 
		}
	}
	return [
		'brace_depth_chg' => $brace_depth_chg,
		'last' => $t
	];
}

function phpsh_read_entry() {
	$line = phpsh_readln(MAIN_PROMPT);
	if(empty($line[0]))
		return null;

	if(isset($line[0]) && $line[0] == '.' && !is_numeric($line[1])) 
		return $line;

	$brace_depth = 0;
	$done = false;
	do {
		$a = phpsh_line_analyze($line);
		$brace_depth += $a['brace_depth_chg'];
		$lines[] = $line;
		if($brace_depth == 0) {
			$done = true;
			$line = implode("\n",$lines);
		} else
			$line = phpsh_readln(CONT_PROMPT);
	} while (!$done);

	return [
		'last' => $a['last'],
		'code' => $line,
	];
}

function phpsh_cmd($cmdstr) {
	if(!$cmdstr) {
		echo "missing phpsh command\n";
		return false;
	}
	$cmd_parts = preg_split("/\s+/",$cmdstr,-1,PREG_SPLIT_NO_EMPTY);

	$cmd = is_array($cmd_parts) ? $cmd_parts[0] : null;
	switch($cmd) {
		case 'q': 
			exit;
		case 's': 
			phpsh_cmd_save($cmd_parts[1] ?? null);
			break;
		case 'i':
		case 'l':
			$histfile = $cmd_parts[1] ?? DEFAULT_HIST;
			if(file_exists($histfile)) 
				phpsh_include($histfile);
			else 
				echo "can't find $histfile\n";
			break;
		case 'r':
			if(file_exists(DEFAULT_CRASH))
				phpsh_include(DEFAULT_CRASH);
			else 
				echo "can't find ",DEFAULT_CRASH,"\n";
			break;
		case 'h': 
			phpsh_cmd_help();
			break;
		default:
			echo "`$cmdstr`: command not found.\n";
			return false;
	}
	return true;
}

function phpsh_include($file) {
	if(preg_match('/phpsh$/',$file)) return true;
	echo "phpsh_include($file)\n";
	return file_exists($file) ? include_once($file) : false;
}

function phpsh_cols() { return (int)(getenv('COLUMNS') ?: `tput cols`); }

function phpsh_objkv($obj) {  return (array)$obj; }

function phpsh_lsaa_str($aa,$entrysep = "\n") { 
	$rv = array('[');
	$cols = phpsh_cols();
	foreach($aa as $k => $v) {
		$maxproplen = $cols - strlen($k) - 8;
		$valstr = phpsh_showVar($v,'');
		array_push($rv,$entrysep,"  ",$k,' => ',substr($valstr,0,$maxproplen),strlen($valstr) > $maxproplen ? '…' : '');
	}
	if(count($aa) > 0) $rv[] = $entrysep;
	$rv[] = ']';
	$rv = implode('',$rv);
	return $rv;
}

function phpsh_showVar($v,$entrysep = "\n") {
	// if(is_object($v) && method_exists($v,'__to_string')) 
	//	return $v->__toString();
	// $rv = '(phpsh doesn\'t know how to string-ify this variable or result)';
	
	if(is_object($v)) 
		return get_class($v).'('.phpsh_showVar((array)$v,$entrysep).')';

	if(is_array($v)) 
		return phpsh_lsaa_str($v,$entrysep);

	if($v === null) 
		return "null";
	else 
		return var_export($v,true);
}

function phpsh_cmd_save($filename,$avoid_last=false) {
	global $history;
	if(!$filename) {
		$filename = DEFAULT_HIST;
		echo "save command .s needs target file, using ",DEFAULT_HIST," in current working directory ",getcwd(),"\n";
	} 
	if($avoid_last) 
		array_pop($history);
	$output = "<?php \n\n".implode(";\n",$history).";";
	if(!file_put_contents($filename,$output))
		echo "error writing file $filename\n";
	else
		echo "saved history to $filename\n";
}

function phpsh_cmd_help() {
	$default_crash = DEFAULT_CRASH;
	echo <<<EOD
Available phpsh commands:
  .h       - prints this command list
  .s <arg> - saves command history to filename <arg>
  .l <arg> - shortcut for include(<arg>)
  .r       - shortcut for include("$default_crash")
  .q       - quit

Beyond that, everything else is simply filtered through PHP's `eval` function. phpsh will attempt to automatically yield a string representation of entries that don't end with a semi-colon or a block delimiter. 

EOD;
}

function phpsh_on_shutdown() {
	$err = error_get_last();	
	if($err && ($err['type'] === E_ERROR)) {
		phpsh_cmd_save(DEFAULT_CRASH);
		echo "history saved to ",DEFAULT_CRASH,", use .r on next run to replay";
	}
	echo "\n";
}
?>
